//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerAudioPlayer.Language {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerAudioPlayer.Language.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 所有文件 的本地化字符串。
        /// </summary>
        internal static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部支持的文件 的本地化字符串。
        /// </summary>
        internal static string AllSupportedFileFilter {
            get {
                return ResourceManager.GetString("AllSupportedFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PowerAudioPlayer 的本地化字符串。
        /// </summary>
        internal static string PAA {
            get {
                return ResourceManager.GetString("PAA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂停 的本地化字符串。
        /// </summary>
        internal static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 播放 的本地化字符串。
        /// </summary>
        internal static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一曲 的本地化字符串。
        /// </summary>
        internal static string SNext {
            get {
                return ResourceManager.GetString("SNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一曲 的本地化字符串。
        /// </summary>
        internal static string SPrevious {
            get {
                return ResourceManager.GetString("SPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知专辑 的本地化字符串。
        /// </summary>
        internal static string UnknowAlbum {
            get {
                return ResourceManager.GetString("UnknowAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知艺术家 的本地化字符串。
        /// </summary>
        internal static string UnknowArtist {
            get {
                return ResourceManager.GetString("UnknowArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知流派 的本地化字符串。
        /// </summary>
        internal static string UnknowGenre {
            get {
                return ResourceManager.GetString("UnknowGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知标题 的本地化字符串。
        /// </summary>
        internal static string UnknowTitle {
            get {
                return ResourceManager.GetString("UnknowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知音轨号 的本地化字符串。
        /// </summary>
        internal static string UnknowTrack {
            get {
                return ResourceManager.GetString("UnknowTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知年份 的本地化字符串。
        /// </summary>
        internal static string UnknowYear {
            get {
                return ResourceManager.GetString("UnknowYear", resourceCulture);
            }
        }
    }
}
